// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensajes vacíos
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

// Información del agente
type AgentInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Platform        string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	PlatformVersion string                 `protobuf:"bytes,4,opt,name=platform_version,json=platformVersion,proto3" json:"platform_version,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	ActiveServers   int32                  `protobuf:"varint,6,opt,name=active_servers,json=activeServers,proto3" json:"active_servers,omitempty"`
	MaxServers      int32                  `protobuf:"varint,7,opt,name=max_servers,json=maxServers,proto3" json:"max_servers,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AgentInfo) GetPlatformVersion() string {
	if x != nil {
		return x.PlatformVersion
	}
	return ""
}

func (x *AgentInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *AgentInfo) GetActiveServers() int32 {
	if x != nil {
		return x.ActiveServers
	}
	return 0
}

func (x *AgentInfo) GetMaxServers() int32 {
	if x != nil {
		return x.MaxServers
	}
	return 0
}

// Métricas del sistema
type SystemMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryTotal   uint64                 `protobuf:"varint,3,opt,name=memory_total,json=memoryTotal,proto3" json:"memory_total,omitempty"`
	MemoryUsed    uint64                 `protobuf:"varint,4,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	MemoryPercent float64                `protobuf:"fixed64,5,opt,name=memory_percent,json=memoryPercent,proto3" json:"memory_percent,omitempty"`
	DiskTotal     uint64                 `protobuf:"varint,6,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	DiskUsed      uint64                 `protobuf:"varint,7,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`
	DiskPercent   float64                `protobuf:"fixed64,8,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	NetworkSent   uint64                 `protobuf:"varint,9,opt,name=network_sent,json=networkSent,proto3" json:"network_sent,omitempty"`
	NetworkRecv   uint64                 `protobuf:"varint,10,opt,name=network_recv,json=networkRecv,proto3" json:"network_recv,omitempty"`
	OpenPorts     []int32                `protobuf:"varint,11,rep,packed,name=open_ports,json=openPorts,proto3" json:"open_ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *SystemMetrics) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SystemMetrics) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *SystemMetrics) GetMemoryTotal() uint64 {
	if x != nil {
		return x.MemoryTotal
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsed() uint64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *SystemMetrics) GetMemoryPercent() float64 {
	if x != nil {
		return x.MemoryPercent
	}
	return 0
}

func (x *SystemMetrics) GetDiskTotal() uint64 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

func (x *SystemMetrics) GetDiskUsed() uint64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *SystemMetrics) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *SystemMetrics) GetNetworkSent() uint64 {
	if x != nil {
		return x.NetworkSent
	}
	return 0
}

func (x *SystemMetrics) GetNetworkRecv() uint64 {
	if x != nil {
		return x.NetworkRecv
	}
	return 0
}

func (x *SystemMetrics) GetOpenPorts() []int32 {
	if x != nil {
		return x.OpenPorts
	}
	return nil
}

// Servidor
type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // paper, purpur, velocity, etc.
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	JavaVersion   string                 `protobuf:"bytes,5,opt,name=java_version,json=javaVersion,proto3" json:"java_version,omitempty"`
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Pid           int32                  `protobuf:"varint,8,opt,name=pid,proto3" json:"pid,omitempty"`
	StartTime     int64                  `protobuf:"varint,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	WorkDir       string                 `protobuf:"bytes,10,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	Config        *ServerConfig          `protobuf:"bytes,11,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ServerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServerInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetJavaVersion() string {
	if x != nil {
		return x.JavaVersion
	}
	return ""
}

func (x *ServerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServerInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ServerInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ServerInfo) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *ServerInfo) GetConfig() *ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ServerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinRam        string                 `protobuf:"bytes,1,opt,name=min_ram,json=minRam,proto3" json:"min_ram,omitempty"`
	MaxRam        string                 `protobuf:"bytes,2,opt,name=max_ram,json=maxRam,proto3" json:"max_ram,omitempty"`
	JavaArgs      []string               `protobuf:"bytes,3,rep,name=java_args,json=javaArgs,proto3" json:"java_args,omitempty"`
	JarFile       string                 `protobuf:"bytes,4,opt,name=jar_file,json=jarFile,proto3" json:"jar_file,omitempty"`
	AutoRestart   bool                   `protobuf:"varint,5,opt,name=auto_restart,json=autoRestart,proto3" json:"auto_restart,omitempty"`
	CustomArgs    map[string]string      `protobuf:"bytes,6,rep,name=custom_args,json=customArgs,proto3" json:"custom_args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ServerConfig) GetMinRam() string {
	if x != nil {
		return x.MinRam
	}
	return ""
}

func (x *ServerConfig) GetMaxRam() string {
	if x != nil {
		return x.MaxRam
	}
	return ""
}

func (x *ServerConfig) GetJavaArgs() []string {
	if x != nil {
		return x.JavaArgs
	}
	return nil
}

func (x *ServerConfig) GetJarFile() string {
	if x != nil {
		return x.JarFile
	}
	return ""
}

func (x *ServerConfig) GetAutoRestart() bool {
	if x != nil {
		return x.AutoRestart
	}
	return false
}

func (x *ServerConfig) GetCustomArgs() map[string]string {
	if x != nil {
		return x.CustomArgs
	}
	return nil
}

type ServerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*ServerInfo          `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerList) Reset() {
	*x = ServerList{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerList) ProtoMessage() {}

func (x *ServerList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerList.ProtoReflect.Descriptor instead.
func (*ServerList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ServerList) GetServers() []*ServerInfo {
	if x != nil {
		return x.Servers
	}
	return nil
}

type ServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRequest) Reset() {
	*x = ServerRequest{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRequest) ProtoMessage() {}

func (x *ServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRequest.ProtoReflect.Descriptor instead.
func (*ServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

type StartServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Config        *ServerConfig          `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartServerRequest) Reset() {
	*x = StartServerRequest{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartServerRequest) ProtoMessage() {}

func (x *StartServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartServerRequest.ProtoReflect.Descriptor instead.
func (*StartServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StartServerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *StartServerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartServerRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StartServerRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StartServerRequest) GetConfig() *ServerConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type ServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Server        *ServerInfo            `protobuf:"bytes,3,opt,name=server,proto3" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerResponse) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

// Comandos
type CommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *CommandRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Output        string                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

// Logs
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Level         string                 `protobuf:"bytes,3,opt,name=level,proto3" json:"level,omitempty"`   // INFO, WARN, ERROR, DEBUG
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"` // STDOUT, STDERR
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Plugin        string                 `protobuf:"bytes,6,opt,name=plugin,proto3" json:"plugin,omitempty"` // plugin que generó el log (si se detecta)
	File          string                 `protobuf:"bytes,7,opt,name=file,proto3" json:"file,omitempty"`     // archivo de origen (si se detecta)
	Line          int32                  `protobuf:"varint,8,opt,name=line,proto3" json:"line,omitempty"`    // línea de origen (si se detecta)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *LogEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogEntry) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *LogEntry) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *LogEntry) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

// Archivos
type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *FileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type FileContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModifiedTime  int64                  `protobuf:"varint,3,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileContent) Reset() {
	*x = FileContent{}
	mi := &file_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileContent) ProtoMessage() {}

func (x *FileContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileContent.ProtoReflect.Descriptor instead.
func (*FileContent) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *FileContent) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileContent) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileContent) GetModifiedTime() int64 {
	if x != nil {
		return x.ModifiedTime
	}
	return 0
}

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	CreateDirs    bool                   `protobuf:"varint,3,opt,name=create_dirs,json=createDirs,proto3" json:"create_dirs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WriteFileRequest) GetCreateDirs() bool {
	if x != nil {
		return x.CreateDirs
	}
	return false
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{15}
}

func (x *FileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryRequest) Reset() {
	*x = DirectoryRequest{}
	mi := &file_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryRequest) ProtoMessage() {}

func (x *DirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryRequest.ProtoReflect.Descriptor instead.
func (*DirectoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *DirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DirectoryRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type FileList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*FileInfo            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileList) Reset() {
	*x = FileList{}
	mi := &file_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileList) ProtoMessage() {}

func (x *FileList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileList.ProtoReflect.Descriptor instead.
func (*FileList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *FileList) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	IsDir         bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	ModifiedTime  int64                  `protobuf:"varint,5,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	Permissions   int32                  `protobuf:"varint,6,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *FileInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetModifiedTime() int64 {
	if x != nil {
		return x.ModifiedTime
	}
	return 0
}

func (x *FileInfo) GetPermissions() int32 {
	if x != nil {
		return x.Permissions
	}
	return 0
}

// Dependencias
type DependenciesStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JavaInstalled   bool                   `protobuf:"varint,1,opt,name=java_installed,json=javaInstalled,proto3" json:"java_installed,omitempty"`
	JavaVersion     string                 `protobuf:"bytes,2,opt,name=java_version,json=javaVersion,proto3" json:"java_version,omitempty"`
	JavaPaths       []string               `protobuf:"bytes,3,rep,name=java_paths,json=javaPaths,proto3" json:"java_paths,omitempty"`
	ScreenInstalled bool                   `protobuf:"varint,4,opt,name=screen_installed,json=screenInstalled,proto3" json:"screen_installed,omitempty"`
	TmuxInstalled   bool                   `protobuf:"varint,5,opt,name=tmux_installed,json=tmuxInstalled,proto3" json:"tmux_installed,omitempty"`
	Environment     map[string]string      `protobuf:"bytes,6,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DependenciesStatus) Reset() {
	*x = DependenciesStatus{}
	mi := &file_proto_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependenciesStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependenciesStatus) ProtoMessage() {}

func (x *DependenciesStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependenciesStatus.ProtoReflect.Descriptor instead.
func (*DependenciesStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{19}
}

func (x *DependenciesStatus) GetJavaInstalled() bool {
	if x != nil {
		return x.JavaInstalled
	}
	return false
}

func (x *DependenciesStatus) GetJavaVersion() string {
	if x != nil {
		return x.JavaVersion
	}
	return ""
}

func (x *DependenciesStatus) GetJavaPaths() []string {
	if x != nil {
		return x.JavaPaths
	}
	return nil
}

func (x *DependenciesStatus) GetScreenInstalled() bool {
	if x != nil {
		return x.ScreenInstalled
	}
	return false
}

func (x *DependenciesStatus) GetTmuxInstalled() bool {
	if x != nil {
		return x.TmuxInstalled
	}
	return false
}

func (x *DependenciesStatus) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type JavaInstallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // 8, 11, 17, 21
	UseSudo       bool                   `protobuf:"varint,2,opt,name=use_sudo,json=useSudo,proto3" json:"use_sudo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JavaInstallRequest) Reset() {
	*x = JavaInstallRequest{}
	mi := &file_proto_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JavaInstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JavaInstallRequest) ProtoMessage() {}

func (x *JavaInstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JavaInstallRequest.ProtoReflect.Descriptor instead.
func (*JavaInstallRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{20}
}

func (x *JavaInstallRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *JavaInstallRequest) GetUseSudo() bool {
	if x != nil {
		return x.UseSudo
	}
	return false
}

type InstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Logs          []string               `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallResponse) Reset() {
	*x = InstallResponse{}
	mi := &file_proto_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallResponse) ProtoMessage() {}

func (x *InstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallResponse.ProtoReflect.Descriptor instead.
func (*InstallResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{21}
}

func (x *InstallResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstallResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Destination   string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`                           // hash para validación
	ServerType    string                 `protobuf:"bytes,4,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"` // paper, purpur, velocity
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_proto_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{22}
}

func (x *DownloadRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DownloadRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *DownloadRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *DownloadRequest) GetServerType() string {
	if x != nil {
		return x.ServerType
	}
	return ""
}

func (x *DownloadRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type DownloadProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Downloaded    int64                  `protobuf:"varint,1,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Percent       float64                `protobuf:"fixed64,3,opt,name=percent,proto3" json:"percent,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Complete      bool                   `protobuf:"varint,5,opt,name=complete,proto3" json:"complete,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadProgress) Reset() {
	*x = DownloadProgress{}
	mi := &file_proto_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadProgress) ProtoMessage() {}

func (x *DownloadProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadProgress.ProtoReflect.Descriptor instead.
func (*DownloadProgress) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{23}
}

func (x *DownloadProgress) GetDownloaded() int64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *DownloadProgress) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DownloadProgress) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *DownloadProgress) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DownloadProgress) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *DownloadProgress) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Health y ping
type PongResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongResponse) Reset() {
	*x = PongResponse{}
	mi := &file_proto_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongResponse) ProtoMessage() {}

func (x *PongResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongResponse.ProtoReflect.Descriptor instead.
func (*PongResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{24}
}

func (x *PongResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PongResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HealthStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Checks        map[string]string      `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthStatus) Reset() {
	*x = HealthStatus{}
	mi := &file_proto_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthStatus) ProtoMessage() {}

func (x *HealthStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthStatus.ProtoReflect.Descriptor instead.
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{25}
}

func (x *HealthStatus) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthStatus) GetChecks() map[string]string {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *HealthStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Gestión de plugins
type InstallPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,3,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	AutoRestart   bool                   `protobuf:"varint,6,opt,name=auto_restart,json=autoRestart,proto3" json:"auto_restart,omitempty"` // reiniciar servidor después de instalar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPluginRequest) Reset() {
	*x = InstallPluginRequest{}
	mi := &file_proto_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginRequest) ProtoMessage() {}

func (x *InstallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPluginRequest.ProtoReflect.Descriptor instead.
func (*InstallPluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{26}
}

func (x *InstallPluginRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *InstallPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *InstallPluginRequest) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *InstallPluginRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *InstallPluginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstallPluginRequest) GetAutoRestart() bool {
	if x != nil {
		return x.AutoRestart
	}
	return false
}

type UninstallPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	DeleteConfig  bool                   `protobuf:"varint,3,opt,name=delete_config,json=deleteConfig,proto3" json:"delete_config,omitempty"` // eliminar archivos de configuración
	DeleteData    bool                   `protobuf:"varint,4,opt,name=delete_data,json=deleteData,proto3" json:"delete_data,omitempty"`       // eliminar datos del plugin
	AutoRestart   bool                   `protobuf:"varint,5,opt,name=auto_restart,json=autoRestart,proto3" json:"auto_restart,omitempty"`    // reiniciar servidor después de desinstalar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallPluginRequest) Reset() {
	*x = UninstallPluginRequest{}
	mi := &file_proto_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallPluginRequest) ProtoMessage() {}

func (x *UninstallPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallPluginRequest.ProtoReflect.Descriptor instead.
func (*UninstallPluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{27}
}

func (x *UninstallPluginRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UninstallPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *UninstallPluginRequest) GetDeleteConfig() bool {
	if x != nil {
		return x.DeleteConfig
	}
	return false
}

func (x *UninstallPluginRequest) GetDeleteData() bool {
	if x != nil {
		return x.DeleteData
	}
	return false
}

func (x *UninstallPluginRequest) GetAutoRestart() bool {
	if x != nil {
		return x.AutoRestart
	}
	return false
}

type UpdatePluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	PluginName    string                 `protobuf:"bytes,2,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,3,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	NewVersion    string                 `protobuf:"bytes,5,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"`
	AutoRestart   bool                   `protobuf:"varint,6,opt,name=auto_restart,json=autoRestart,proto3" json:"auto_restart,omitempty"` // reiniciar servidor después de actualizar
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePluginRequest) Reset() {
	*x = UpdatePluginRequest{}
	mi := &file_proto_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePluginRequest) ProtoMessage() {}

func (x *UpdatePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePluginRequest.ProtoReflect.Descriptor instead.
func (*UpdatePluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{28}
}

func (x *UpdatePluginRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdatePluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *UpdatePluginRequest) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *UpdatePluginRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UpdatePluginRequest) GetNewVersion() string {
	if x != nil {
		return x.NewVersion
	}
	return ""
}

func (x *UpdatePluginRequest) GetAutoRestart() bool {
	if x != nil {
		return x.AutoRestart
	}
	return false
}

type ListPluginsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerId        string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	IncludeDisabled bool                   `protobuf:"varint,2,opt,name=include_disabled,json=includeDisabled,proto3" json:"include_disabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_proto_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{29}
}

func (x *ListPluginsRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ListPluginsRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

type PluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Plugin        *PluginInfo            `protobuf:"bytes,3,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginResponse) Reset() {
	*x = PluginResponse{}
	mi := &file_proto_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginResponse) ProtoMessage() {}

func (x *PluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginResponse.ProtoReflect.Descriptor instead.
func (*PluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{30}
}

func (x *PluginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PluginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginResponse) GetPlugin() *PluginInfo {
	if x != nil {
		return x.Plugin
	}
	return nil
}

type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Enabled       bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	FileName      string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	InstalledAt   int64                  `protobuf:"varint,8,opt,name=installed_at,json=installedAt,proto3" json:"installed_at,omitempty"`
	Dependencies  []string               `protobuf:"bytes,9,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_proto_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{31}
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *PluginInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *PluginInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *PluginInfo) GetInstalledAt() int64 {
	if x != nil {
		return x.InstalledAt
	}
	return 0
}

func (x *PluginInfo) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type PluginList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginInfo          `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginList) Reset() {
	*x = PluginList{}
	mi := &file_proto_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginList) ProtoMessage() {}

func (x *PluginList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginList.ProtoReflect.Descriptor instead.
func (*PluginList) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{32}
}

func (x *PluginList) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

func (x *PluginList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Gestión de backups
type CreateBackupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerId       string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	BackupType     string                 `protobuf:"bytes,2,opt,name=backup_type,json=backupType,proto3" json:"backup_type,omitempty"`  // full, world, plugins, config
	Destination    string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`                  // ruta donde guardar el backup
	Compression    string                 `protobuf:"bytes,4,opt,name=compression,proto3" json:"compression,omitempty"`                  // gzip, bzip2, none
	StopServer     bool                   `protobuf:"varint,5,opt,name=stop_server,json=stopServer,proto3" json:"stop_server,omitempty"` // detener servidor antes de hacer backup
	IncludeWorld   bool                   `protobuf:"varint,6,opt,name=include_world,json=includeWorld,proto3" json:"include_world,omitempty"`
	IncludePlugins bool                   `protobuf:"varint,7,opt,name=include_plugins,json=includePlugins,proto3" json:"include_plugins,omitempty"`
	IncludeConfig  bool                   `protobuf:"varint,8,opt,name=include_config,json=includeConfig,proto3" json:"include_config,omitempty"`
	IncludeLogs    bool                   `protobuf:"varint,9,opt,name=include_logs,json=includeLogs,proto3" json:"include_logs,omitempty"`
	ExcludePaths   []string               `protobuf:"bytes,10,rep,name=exclude_paths,json=excludePaths,proto3" json:"exclude_paths,omitempty"` // rutas a excluir
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateBackupRequest) Reset() {
	*x = CreateBackupRequest{}
	mi := &file_proto_agent_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupRequest) ProtoMessage() {}

func (x *CreateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{33}
}

func (x *CreateBackupRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateBackupRequest) GetBackupType() string {
	if x != nil {
		return x.BackupType
	}
	return ""
}

func (x *CreateBackupRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateBackupRequest) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *CreateBackupRequest) GetStopServer() bool {
	if x != nil {
		return x.StopServer
	}
	return false
}

func (x *CreateBackupRequest) GetIncludeWorld() bool {
	if x != nil {
		return x.IncludeWorld
	}
	return false
}

func (x *CreateBackupRequest) GetIncludePlugins() bool {
	if x != nil {
		return x.IncludePlugins
	}
	return false
}

func (x *CreateBackupRequest) GetIncludeConfig() bool {
	if x != nil {
		return x.IncludeConfig
	}
	return false
}

func (x *CreateBackupRequest) GetIncludeLogs() bool {
	if x != nil {
		return x.IncludeLogs
	}
	return false
}

func (x *CreateBackupRequest) GetExcludePaths() []string {
	if x != nil {
		return x.ExcludePaths
	}
	return nil
}

type CreateBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	BackupPath    string                 `protobuf:"bytes,3,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Checksum      string                 `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"` // SHA256
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupResponse) Reset() {
	*x = CreateBackupResponse{}
	mi := &file_proto_agent_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupResponse) ProtoMessage() {}

func (x *CreateBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupResponse.ProtoReflect.Descriptor instead.
func (*CreateBackupResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{34}
}

func (x *CreateBackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateBackupResponse) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *CreateBackupResponse) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *CreateBackupResponse) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *CreateBackupResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type RestoreBackupRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServerId            string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	BackupPath          string                 `protobuf:"bytes,2,opt,name=backup_path,json=backupPath,proto3" json:"backup_path,omitempty"`
	StopServer          bool                   `protobuf:"varint,3,opt,name=stop_server,json=stopServer,proto3" json:"stop_server,omitempty"` // detener servidor antes de restaurar
	RestoreWorld        bool                   `protobuf:"varint,4,opt,name=restore_world,json=restoreWorld,proto3" json:"restore_world,omitempty"`
	RestorePlugins      bool                   `protobuf:"varint,5,opt,name=restore_plugins,json=restorePlugins,proto3" json:"restore_plugins,omitempty"`
	RestoreConfig       bool                   `protobuf:"varint,6,opt,name=restore_config,json=restoreConfig,proto3" json:"restore_config,omitempty"`
	BackupBeforeRestore bool                   `protobuf:"varint,7,opt,name=backup_before_restore,json=backupBeforeRestore,proto3" json:"backup_before_restore,omitempty"` // crear backup de seguridad antes de restaurar
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RestoreBackupRequest) Reset() {
	*x = RestoreBackupRequest{}
	mi := &file_proto_agent_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupRequest) ProtoMessage() {}

func (x *RestoreBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupRequest.ProtoReflect.Descriptor instead.
func (*RestoreBackupRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{35}
}

func (x *RestoreBackupRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RestoreBackupRequest) GetBackupPath() string {
	if x != nil {
		return x.BackupPath
	}
	return ""
}

func (x *RestoreBackupRequest) GetStopServer() bool {
	if x != nil {
		return x.StopServer
	}
	return false
}

func (x *RestoreBackupRequest) GetRestoreWorld() bool {
	if x != nil {
		return x.RestoreWorld
	}
	return false
}

func (x *RestoreBackupRequest) GetRestorePlugins() bool {
	if x != nil {
		return x.RestorePlugins
	}
	return false
}

func (x *RestoreBackupRequest) GetRestoreConfig() bool {
	if x != nil {
		return x.RestoreConfig
	}
	return false
}

func (x *RestoreBackupRequest) GetBackupBeforeRestore() bool {
	if x != nil {
		return x.BackupBeforeRestore
	}
	return false
}

type RestoreBackupResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DurationMs       int64                  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	SafetyBackupPath string                 `protobuf:"bytes,4,opt,name=safety_backup_path,json=safetyBackupPath,proto3" json:"safety_backup_path,omitempty"` // path del backup de seguridad si se creó
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RestoreBackupResponse) Reset() {
	*x = RestoreBackupResponse{}
	mi := &file_proto_agent_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupResponse) ProtoMessage() {}

func (x *RestoreBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupResponse.ProtoReflect.Descriptor instead.
func (*RestoreBackupResponse) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{36}
}

func (x *RestoreBackupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreBackupResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RestoreBackupResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RestoreBackupResponse) GetSafetyBackupPath() string {
	if x != nil {
		return x.SafetyBackupPath
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x05agent\"\a\n" +
	"\x05Empty\"\xf6\x01\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12)\n" +
	"\x10platform_version\x18\x04 \x01(\tR\x0fplatformVersion\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x03R\ruptimeSeconds\x12%\n" +
	"\x0eactive_servers\x18\x06 \x01(\x05R\ractiveServers\x12\x1f\n" +
	"\vmax_servers\x18\a \x01(\x05R\n" +
	"maxServers\"\xfd\x02\n" +
	"\rSystemMetrics\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_total\x18\x03 \x01(\x04R\vmemoryTotal\x12\x1f\n" +
	"\vmemory_used\x18\x04 \x01(\x04R\n" +
	"memoryUsed\x12%\n" +
	"\x0ememory_percent\x18\x05 \x01(\x01R\rmemoryPercent\x12\x1d\n" +
	"\n" +
	"disk_total\x18\x06 \x01(\x04R\tdiskTotal\x12\x1b\n" +
	"\tdisk_used\x18\a \x01(\x04R\bdiskUsed\x12!\n" +
	"\fdisk_percent\x18\b \x01(\x01R\vdiskPercent\x12!\n" +
	"\fnetwork_sent\x18\t \x01(\x04R\vnetworkSent\x12!\n" +
	"\fnetwork_recv\x18\n" +
	" \x01(\x04R\vnetworkRecv\x12\x1d\n" +
	"\n" +
	"open_ports\x18\v \x03(\x05R\topenPorts\"\xa6\x02\n" +
	"\n" +
	"ServerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12!\n" +
	"\fjava_version\x18\x05 \x01(\tR\vjavaVersion\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x10\n" +
	"\x03pid\x18\b \x01(\x05R\x03pid\x12\x1d\n" +
	"\n" +
	"start_time\x18\t \x01(\x03R\tstartTime\x12\x19\n" +
	"\bwork_dir\x18\n" +
	" \x01(\tR\aworkDir\x12+\n" +
	"\x06config\x18\v \x01(\v2\x13.agent.ServerConfigR\x06config\"\xa0\x02\n" +
	"\fServerConfig\x12\x17\n" +
	"\amin_ram\x18\x01 \x01(\tR\x06minRam\x12\x17\n" +
	"\amax_ram\x18\x02 \x01(\tR\x06maxRam\x12\x1b\n" +
	"\tjava_args\x18\x03 \x03(\tR\bjavaArgs\x12\x19\n" +
	"\bjar_file\x18\x04 \x01(\tR\ajarFile\x12!\n" +
	"\fauto_restart\x18\x05 \x01(\bR\vautoRestart\x12D\n" +
	"\vcustom_args\x18\x06 \x03(\v2#.agent.ServerConfig.CustomArgsEntryR\n" +
	"customArgs\x1a=\n" +
	"\x0fCustomArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\n" +
	"ServerList\x12+\n" +
	"\aservers\x18\x01 \x03(\v2\x11.agent.ServerInfoR\aservers\",\n" +
	"\rServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\"\xa0\x01\n" +
	"\x12StartServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12+\n" +
	"\x06config\x18\x05 \x01(\v2\x13.agent.ServerConfigR\x06config\"o\n" +
	"\x0eServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x06server\x18\x03 \x01(\v2\x11.agent.ServerInfoR\x06server\"G\n" +
	"\x0eCommandRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\"]\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06output\x18\x03 \x01(\tR\x06output\"\xcd\x01\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\tR\x05level\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06plugin\x18\x06 \x01(\tR\x06plugin\x12\x12\n" +
	"\x04file\x18\a \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\b \x01(\x05R\x04line\"Q\n" +
	"\vFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\"`\n" +
	"\vFileContent\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12#\n" +
	"\rmodified_time\x18\x03 \x01(\x03R\fmodifiedTime\"a\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x1f\n" +
	"\vcreate_dirs\x18\x03 \x01(\bR\n" +
	"createDirs\"B\n" +
	"\fFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x10DirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"1\n" +
	"\bFileList\x12%\n" +
	"\x05files\x18\x01 \x03(\v2\x0f.agent.FileInfoR\x05files\"\xa4\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\x12#\n" +
	"\rmodified_time\x18\x05 \x01(\x03R\fmodifiedTime\x12 \n" +
	"\vpermissions\x18\x06 \x01(\x05R\vpermissions\"\xdd\x02\n" +
	"\x12DependenciesStatus\x12%\n" +
	"\x0ejava_installed\x18\x01 \x01(\bR\rjavaInstalled\x12!\n" +
	"\fjava_version\x18\x02 \x01(\tR\vjavaVersion\x12\x1d\n" +
	"\n" +
	"java_paths\x18\x03 \x03(\tR\tjavaPaths\x12)\n" +
	"\x10screen_installed\x18\x04 \x01(\bR\x0fscreenInstalled\x12%\n" +
	"\x0etmux_installed\x18\x05 \x01(\bR\rtmuxInstalled\x12L\n" +
	"\venvironment\x18\x06 \x03(\v2*.agent.DependenciesStatus.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x12JavaInstallRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x19\n" +
	"\buse_sudo\x18\x02 \x01(\bR\auseSudo\"Y\n" +
	"\x0fInstallResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04logs\x18\x03 \x03(\tR\x04logs\"\x98\x01\n" +
	"\x0fDownloadRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x1f\n" +
	"\vserver_type\x18\x04 \x01(\tR\n" +
	"serverType\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\"\xac\x01\n" +
	"\x10DownloadProgress\x12\x1e\n" +
	"\n" +
	"downloaded\x18\x01 \x01(\x03R\n" +
	"downloaded\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x18\n" +
	"\apercent\x18\x03 \x01(\x01R\apercent\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1a\n" +
	"\bcomplete\x18\x05 \x01(\bR\bcomplete\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"F\n" +
	"\fPongResponse\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd2\x01\n" +
	"\fHealthStatus\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x127\n" +
	"\x06checks\x18\x03 \x03(\v2\x1f.agent.HealthStatus.ChecksEntryR\x06checks\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x1a9\n" +
	"\vChecksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\x14InstallPluginRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\x12!\n" +
	"\fdownload_url\x18\x03 \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12!\n" +
	"\fauto_restart\x18\x06 \x01(\bR\vautoRestart\"\xbf\x01\n" +
	"\x16UninstallPluginRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\x12#\n" +
	"\rdelete_config\x18\x03 \x01(\bR\fdeleteConfig\x12\x1f\n" +
	"\vdelete_data\x18\x04 \x01(\bR\n" +
	"deleteData\x12!\n" +
	"\fauto_restart\x18\x05 \x01(\bR\vautoRestart\"\xd7\x01\n" +
	"\x13UpdatePluginRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vplugin_name\x18\x02 \x01(\tR\n" +
	"pluginName\x12!\n" +
	"\fdownload_url\x18\x03 \x01(\tR\vdownloadUrl\x12\x1b\n" +
	"\tfile_name\x18\x04 \x01(\tR\bfileName\x12\x1f\n" +
	"\vnew_version\x18\x05 \x01(\tR\n" +
	"newVersion\x12!\n" +
	"\fauto_restart\x18\x06 \x01(\bR\vautoRestart\"\\\n" +
	"\x12ListPluginsRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12)\n" +
	"\x10include_disabled\x18\x02 \x01(\bR\x0fincludeDisabled\"o\n" +
	"\x0ePluginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x06plugin\x18\x03 \x01(\v2\x11.agent.PluginInfoR\x06plugin\"\x8f\x02\n" +
	"\n" +
	"PluginInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12!\n" +
	"\finstalled_at\x18\b \x01(\x03R\vinstalledAt\x12\"\n" +
	"\fdependencies\x18\t \x03(\tR\fdependencies\"O\n" +
	"\n" +
	"PluginList\x12+\n" +
	"\aplugins\x18\x01 \x03(\v2\x11.agent.PluginInfoR\aplugins\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xf5\x02\n" +
	"\x13CreateBackupRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vbackup_type\x18\x02 \x01(\tR\n" +
	"backupType\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12 \n" +
	"\vcompression\x18\x04 \x01(\tR\vcompression\x12\x1f\n" +
	"\vstop_server\x18\x05 \x01(\bR\n" +
	"stopServer\x12#\n" +
	"\rinclude_world\x18\x06 \x01(\bR\fincludeWorld\x12'\n" +
	"\x0finclude_plugins\x18\a \x01(\bR\x0eincludePlugins\x12%\n" +
	"\x0einclude_config\x18\b \x01(\bR\rincludeConfig\x12!\n" +
	"\finclude_logs\x18\t \x01(\bR\vincludeLogs\x12#\n" +
	"\rexclude_paths\x18\n" +
	" \x03(\tR\fexcludePaths\"\xc7\x01\n" +
	"\x14CreateBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vbackup_path\x18\x03 \x01(\tR\n" +
	"backupPath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\"\x9e\x02\n" +
	"\x14RestoreBackupRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vbackup_path\x18\x02 \x01(\tR\n" +
	"backupPath\x12\x1f\n" +
	"\vstop_server\x18\x03 \x01(\bR\n" +
	"stopServer\x12#\n" +
	"\rrestore_world\x18\x04 \x01(\bR\frestoreWorld\x12'\n" +
	"\x0frestore_plugins\x18\x05 \x01(\bR\x0erestorePlugins\x12%\n" +
	"\x0erestore_config\x18\x06 \x01(\bR\rrestoreConfig\x122\n" +
	"\x15backup_before_restore\x18\a \x01(\bR\x13backupBeforeRestore\"\x9a\x01\n" +
	"\x15RestoreBackupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12,\n" +
	"\x12safety_backup_path\x18\x04 \x01(\tR\x10safetyBackupPath2\xf6\n" +
	"\n" +
	"\fAgentService\x12.\n" +
	"\fGetAgentInfo\x12\f.agent.Empty\x1a\x10.agent.AgentInfo\x126\n" +
	"\x10GetSystemMetrics\x12\f.agent.Empty\x1a\x14.agent.SystemMetrics\x12.\n" +
	"\vListServers\x12\f.agent.Empty\x1a\x11.agent.ServerList\x124\n" +
	"\tGetServer\x12\x14.agent.ServerRequest\x1a\x11.agent.ServerInfo\x12?\n" +
	"\vStartServer\x12\x19.agent.StartServerRequest\x1a\x15.agent.ServerResponse\x129\n" +
	"\n" +
	"StopServer\x12\x14.agent.ServerRequest\x1a\x15.agent.ServerResponse\x12<\n" +
	"\rRestartServer\x12\x14.agent.ServerRequest\x1a\x15.agent.ServerResponse\x12<\n" +
	"\vSendCommand\x12\x15.agent.CommandRequest\x1a\x16.agent.CommandResponse\x125\n" +
	"\n" +
	"StreamLogs\x12\x14.agent.ServerRequest\x1a\x0f.agent.LogEntry0\x01\x122\n" +
	"\bReadFile\x12\x12.agent.FileRequest\x1a\x12.agent.FileContent\x129\n" +
	"\tWriteFile\x12\x17.agent.WriteFileRequest\x1a\x13.agent.FileResponse\x125\n" +
	"\tListFiles\x12\x17.agent.DirectoryRequest\x1a\x0f.agent.FileList\x12C\n" +
	"\rInstallPlugin\x12\x1b.agent.InstallPluginRequest\x1a\x15.agent.PluginResponse\x12G\n" +
	"\x0fUninstallPlugin\x12\x1d.agent.UninstallPluginRequest\x1a\x15.agent.PluginResponse\x12A\n" +
	"\fUpdatePlugin\x12\x1a.agent.UpdatePluginRequest\x1a\x15.agent.PluginResponse\x12;\n" +
	"\vListPlugins\x12\x19.agent.ListPluginsRequest\x1a\x11.agent.PluginList\x12G\n" +
	"\fCreateBackup\x12\x1a.agent.CreateBackupRequest\x1a\x1b.agent.CreateBackupResponse\x12J\n" +
	"\rRestoreBackup\x12\x1b.agent.RestoreBackupRequest\x1a\x1c.agent.RestoreBackupResponse\x12<\n" +
	"\x11CheckDependencies\x12\f.agent.Empty\x1a\x19.agent.DependenciesStatus\x12@\n" +
	"\vInstallJava\x12\x19.agent.JavaInstallRequest\x1a\x16.agent.InstallResponse\x12C\n" +
	"\x0eDownloadServer\x12\x16.agent.DownloadRequest\x1a\x17.agent.DownloadProgress0\x01\x12)\n" +
	"\x04Ping\x12\f.agent.Empty\x1a\x13.agent.PongResponse\x120\n" +
	"\vHealthCheck\x12\f.agent.Empty\x1a\x13.agent.HealthStatusB\x1fZ\x1dgithub.com/aymc/backend/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_proto_agent_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: agent.Empty
	(*AgentInfo)(nil),              // 1: agent.AgentInfo
	(*SystemMetrics)(nil),          // 2: agent.SystemMetrics
	(*ServerInfo)(nil),             // 3: agent.ServerInfo
	(*ServerConfig)(nil),           // 4: agent.ServerConfig
	(*ServerList)(nil),             // 5: agent.ServerList
	(*ServerRequest)(nil),          // 6: agent.ServerRequest
	(*StartServerRequest)(nil),     // 7: agent.StartServerRequest
	(*ServerResponse)(nil),         // 8: agent.ServerResponse
	(*CommandRequest)(nil),         // 9: agent.CommandRequest
	(*CommandResponse)(nil),        // 10: agent.CommandResponse
	(*LogEntry)(nil),               // 11: agent.LogEntry
	(*FileRequest)(nil),            // 12: agent.FileRequest
	(*FileContent)(nil),            // 13: agent.FileContent
	(*WriteFileRequest)(nil),       // 14: agent.WriteFileRequest
	(*FileResponse)(nil),           // 15: agent.FileResponse
	(*DirectoryRequest)(nil),       // 16: agent.DirectoryRequest
	(*FileList)(nil),               // 17: agent.FileList
	(*FileInfo)(nil),               // 18: agent.FileInfo
	(*DependenciesStatus)(nil),     // 19: agent.DependenciesStatus
	(*JavaInstallRequest)(nil),     // 20: agent.JavaInstallRequest
	(*InstallResponse)(nil),        // 21: agent.InstallResponse
	(*DownloadRequest)(nil),        // 22: agent.DownloadRequest
	(*DownloadProgress)(nil),       // 23: agent.DownloadProgress
	(*PongResponse)(nil),           // 24: agent.PongResponse
	(*HealthStatus)(nil),           // 25: agent.HealthStatus
	(*InstallPluginRequest)(nil),   // 26: agent.InstallPluginRequest
	(*UninstallPluginRequest)(nil), // 27: agent.UninstallPluginRequest
	(*UpdatePluginRequest)(nil),    // 28: agent.UpdatePluginRequest
	(*ListPluginsRequest)(nil),     // 29: agent.ListPluginsRequest
	(*PluginResponse)(nil),         // 30: agent.PluginResponse
	(*PluginInfo)(nil),             // 31: agent.PluginInfo
	(*PluginList)(nil),             // 32: agent.PluginList
	(*CreateBackupRequest)(nil),    // 33: agent.CreateBackupRequest
	(*CreateBackupResponse)(nil),   // 34: agent.CreateBackupResponse
	(*RestoreBackupRequest)(nil),   // 35: agent.RestoreBackupRequest
	(*RestoreBackupResponse)(nil),  // 36: agent.RestoreBackupResponse
	nil,                            // 37: agent.ServerConfig.CustomArgsEntry
	nil,                            // 38: agent.DependenciesStatus.EnvironmentEntry
	nil,                            // 39: agent.HealthStatus.ChecksEntry
}
var file_proto_agent_proto_depIdxs = []int32{
	4,  // 0: agent.ServerInfo.config:type_name -> agent.ServerConfig
	37, // 1: agent.ServerConfig.custom_args:type_name -> agent.ServerConfig.CustomArgsEntry
	3,  // 2: agent.ServerList.servers:type_name -> agent.ServerInfo
	4,  // 3: agent.StartServerRequest.config:type_name -> agent.ServerConfig
	3,  // 4: agent.ServerResponse.server:type_name -> agent.ServerInfo
	18, // 5: agent.FileList.files:type_name -> agent.FileInfo
	38, // 6: agent.DependenciesStatus.environment:type_name -> agent.DependenciesStatus.EnvironmentEntry
	39, // 7: agent.HealthStatus.checks:type_name -> agent.HealthStatus.ChecksEntry
	31, // 8: agent.PluginResponse.plugin:type_name -> agent.PluginInfo
	31, // 9: agent.PluginList.plugins:type_name -> agent.PluginInfo
	0,  // 10: agent.AgentService.GetAgentInfo:input_type -> agent.Empty
	0,  // 11: agent.AgentService.GetSystemMetrics:input_type -> agent.Empty
	0,  // 12: agent.AgentService.ListServers:input_type -> agent.Empty
	6,  // 13: agent.AgentService.GetServer:input_type -> agent.ServerRequest
	7,  // 14: agent.AgentService.StartServer:input_type -> agent.StartServerRequest
	6,  // 15: agent.AgentService.StopServer:input_type -> agent.ServerRequest
	6,  // 16: agent.AgentService.RestartServer:input_type -> agent.ServerRequest
	9,  // 17: agent.AgentService.SendCommand:input_type -> agent.CommandRequest
	6,  // 18: agent.AgentService.StreamLogs:input_type -> agent.ServerRequest
	12, // 19: agent.AgentService.ReadFile:input_type -> agent.FileRequest
	14, // 20: agent.AgentService.WriteFile:input_type -> agent.WriteFileRequest
	16, // 21: agent.AgentService.ListFiles:input_type -> agent.DirectoryRequest
	26, // 22: agent.AgentService.InstallPlugin:input_type -> agent.InstallPluginRequest
	27, // 23: agent.AgentService.UninstallPlugin:input_type -> agent.UninstallPluginRequest
	28, // 24: agent.AgentService.UpdatePlugin:input_type -> agent.UpdatePluginRequest
	29, // 25: agent.AgentService.ListPlugins:input_type -> agent.ListPluginsRequest
	33, // 26: agent.AgentService.CreateBackup:input_type -> agent.CreateBackupRequest
	35, // 27: agent.AgentService.RestoreBackup:input_type -> agent.RestoreBackupRequest
	0,  // 28: agent.AgentService.CheckDependencies:input_type -> agent.Empty
	20, // 29: agent.AgentService.InstallJava:input_type -> agent.JavaInstallRequest
	22, // 30: agent.AgentService.DownloadServer:input_type -> agent.DownloadRequest
	0,  // 31: agent.AgentService.Ping:input_type -> agent.Empty
	0,  // 32: agent.AgentService.HealthCheck:input_type -> agent.Empty
	1,  // 33: agent.AgentService.GetAgentInfo:output_type -> agent.AgentInfo
	2,  // 34: agent.AgentService.GetSystemMetrics:output_type -> agent.SystemMetrics
	5,  // 35: agent.AgentService.ListServers:output_type -> agent.ServerList
	3,  // 36: agent.AgentService.GetServer:output_type -> agent.ServerInfo
	8,  // 37: agent.AgentService.StartServer:output_type -> agent.ServerResponse
	8,  // 38: agent.AgentService.StopServer:output_type -> agent.ServerResponse
	8,  // 39: agent.AgentService.RestartServer:output_type -> agent.ServerResponse
	10, // 40: agent.AgentService.SendCommand:output_type -> agent.CommandResponse
	11, // 41: agent.AgentService.StreamLogs:output_type -> agent.LogEntry
	13, // 42: agent.AgentService.ReadFile:output_type -> agent.FileContent
	15, // 43: agent.AgentService.WriteFile:output_type -> agent.FileResponse
	17, // 44: agent.AgentService.ListFiles:output_type -> agent.FileList
	30, // 45: agent.AgentService.InstallPlugin:output_type -> agent.PluginResponse
	30, // 46: agent.AgentService.UninstallPlugin:output_type -> agent.PluginResponse
	30, // 47: agent.AgentService.UpdatePlugin:output_type -> agent.PluginResponse
	32, // 48: agent.AgentService.ListPlugins:output_type -> agent.PluginList
	34, // 49: agent.AgentService.CreateBackup:output_type -> agent.CreateBackupResponse
	36, // 50: agent.AgentService.RestoreBackup:output_type -> agent.RestoreBackupResponse
	19, // 51: agent.AgentService.CheckDependencies:output_type -> agent.DependenciesStatus
	21, // 52: agent.AgentService.InstallJava:output_type -> agent.InstallResponse
	23, // 53: agent.AgentService.DownloadServer:output_type -> agent.DownloadProgress
	24, // 54: agent.AgentService.Ping:output_type -> agent.PongResponse
	25, // 55: agent.AgentService.HealthCheck:output_type -> agent.HealthStatus
	33, // [33:56] is the sub-list for method output_type
	10, // [10:33] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
